### ISSUE TITLE
等級定義與專案名稱不合

### ISSUE THREAD

**Issue by snyoung** [tpai/taiwan-travel-level#6]
專案名稱叫taiwan-travel-level（台灣旅行等級），網址開頭用的也是travel

但是要住過超過一個月以上才有超過1的級數，這個量表顯示的是居住等級而非旅行等級

**Comment by tpai** [comment]
對欸

當初在開發的時候根本沒想這麼多 囧>

確實蠻有道理的，不過 naming issue 暫時不會列入修改

還是很感謝你的意見 👍
