### ISSUE TITLE
不能玩

### ISSUE THREAD

**Issue by MidoCode** [tpai/taiwan-travel-level#7]
Edge／IE都不能跑。

**Comment by tpai** [comment]
Working on it...

**Comment by tpai** [comment]
上了一版，試試看吧。

目前不會向下支援更舊的瀏覽器了

歡迎開 PR 💪

**Comment by kai1114** [comment]
還是沒辦法用耶
用了手機、電腦
各個瀏覽器都一樣

**Comment by tpai** [comment]
@kai1114 方便提供 iOS 版本、瀏覽器和瀏覽器版本嗎？

**Comment by kai1114** [comment]
iOS 11.1.3
手機用 chrome safari都沒反應

電腦用 
Vivaldi 1.15
Chrome IE11 也都沒辦法

早些時候可以用的朋友說
現在他用也沒反應了

**Comment by tpai** [comment]
因為我手邊只有 mac 和 iOS 的機器，而且都更新到最新版本。

所以可能需要有相關裝置的大大們幫看一下 Code

請求 PR 支援 🙏 

jQuery 部分，已經拔掉了，[I think I might not need jQuery](https://github.com/tpai/taiwan-travel-level/commit/7da7e05cf65a0848e62e5bbc53bede892ff37444)，現在絕大部分都是用原生 JS 寫，但是不確定我是否有漏了什麼。

Cache 部分，每次 push 會清 CDN cache 和[清 Client Browser Cache](https://github.com/tpai/taiwan-travel-level/commit/6214729b543457b50b52474e6670beedc38314b2)，到 Server Side 那端應該是沒什麼問題才對。

不要問我為什麼不用 React, Webpack 這類的 fancy library or tool，因為當初只是想快快做完這個 side project 來玩而已... QQ

`Hail Vanilla JS`

**Comment by cwchien** [comment]
我這邊的測試結果：
- Windows 10
  - Edge 地圖可正常顯示，但 hover 沒有反應也無法點選
  - IE 地圖縮成一團，無法正常顯示，當然 hover 沒有反應也無法點選
  - Chrome 67.0.3396.62 可正常點選及計分
- Ubuntu 18.04
  - Chrome 67.0.3396.62 可正常點選及計分
- 紅米 Note 3 (Android 6.0.1)
  - Chrome 67.0.3396.68 可正常點選及計分
  - Firefox Focus 5.0 (Build #21342112) 可正常點選及計分
- iPad mini 2 (iOS 11.4)
  - Firefox 12.0 (10862) 可正常點選及計分

目前看起來 IE 系列的全軍覆沒外，Chrome 和 Firefox 應該是 OK 的，建議無法用這兩個瀏覽器玩的人，查看看是不是什麼設定阻擋了 Javascript 的執行

**Comment by pentwo** [comment]
### Mac OS 10.13.5
- Safari 11.1.1 
- Firefox Quantum 61.0b8
- Chrome 66.0.3359.181

以上都可正常點選及計分

就連上面 @kai1114 所說的 Vivaldi 1.15都正常

**Comment by tpai** [comment]
感謝 @cwchien @pentwo 協助

剛剛翻了一下 [caniuse](https://caniuse.com/#feat=svg)

> IE9-11 desktop & mobile don't properly scale SVG files.

比 IE8 更舊（含 IE8）基本上是不支援 SVG 的，只能說聲抱歉了，剩下的 IE 版本跟 Edge 似乎無法正常縮放 SVG，不過只要定義好 `width` 跟 `height` attribute 似乎可以暫解，我待會試試。

> Ref: https://codepen.io/tomByrer/pen/qEBbzw?editors=110

**Comment by tpai** [comment]
修正了一些舊瀏覽器的共同問題，再麻煩各位試試 IE 跟 Edge 了 <(_ _)>

* [canvas.toBlob polyfill](https://github.com/tpai/taiwan-travel-level/commit/b1d455d315b36db0baf2e420fdb6d3b5ec9bd18f)
* [Object.assign polyfill](https://github.com/tpai/taiwan-travel-level/commit/712bcf09d32f52b852677b7af93afa09fbf6404d)
* [svg scaling issue in IE](https://github.com/tpai/taiwan-travel-level/commit/8194ffe719231d7c8d14f262e53aacb6be49157a)

**Comment by cwchien** [comment]
Windows 10 上測試 Edge 和 IE 11 已可正常點選及計分了 :D

**Comment by tpai** [comment]
@cwchien 非常感謝 👍
